/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersManagerFrame.java
 *
 * Created on 24-jun-2009, 21:30:28
 */

package org.jecars.client.gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jecars.client.JC_Clientable;
import org.jecars.client.JC_Factory;
import org.jecars.client.scripts.JCS_defaultScript;
import org.jecars.client.scripts.JCS_scriptClient;

/**
 *
 * @author weert
 */
public class UsersManagerFrame extends javax.swing.JFrame {

    /** Creates new form UsersManagerFrame */
    public UsersManagerFrame() {
      initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagerPanel1 = new org.jecars.client.gui.UserManagerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserManager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main( String args[] ) {
        try {
          UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
        } catch( Exception e ) {
          e.printStackTrace();
        }

        final JCS_defaultScript ds = new JCS_defaultScript( args );

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              try {
                UsersManagerFrame umf = new UsersManagerFrame();
                JC_Clientable client = JC_Factory.createClient( ds.mJeCARSServer );
                client.setCredentials( ds.mUsername, ds.mPassword.toCharArray() );
                umf.userManagerPanel1.setClient( client );
                umf.setVisible(true);
              } catch( Exception e ) {
                e.printStackTrace();
              }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected org.jecars.client.gui.UserManagerPanel userManagerPanel1;
    // End of variables declaration//GEN-END:variables

}
