/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WB_UserFrame.java
 *
 * Created on 13-Apr-2010, 15:22:19
 */

package org.jecars.wb;

//import org.jdesktop.swingx.JXLoginDialog;
import org.jdesktop.swingx.JXLoginDialog;
import org.jdesktop.swingx.JXLoginPane;
import org.jecars.client.scripts.JCS_defaultScript;

/**
 *
 * @author weert
 */
public class WB_UserFrame extends javax.swing.JFrame {

 
    /** Creates new form WB_UserFrame */
    public WB_UserFrame() {
      initComponents();
      wB_UserPanel1.setFrame( this );
      return;
    }

    /** setDefaultScript
     * 
     * @param pScript
     */
    public boolean setDefaultScript( final JCS_defaultScript pScript ) {
      if ("".equals( pScript.mUsername )) {
        // **** Ask for credentials
        final JXLoginDialog ld = new JXLoginDialog( this,  "Enter credentials for the user to be edited", true );
        final JXLoginPane lp = ld.getPanel();
        ld.setAlwaysOnTop( true );
        ld.setVisible( true );

        if (lp.getStatus()==JXLoginPane.Status.CANCELLED) {
          return false;
        } else {
          pScript.mUsername = lp.getUserName();
          pScript.mPassword = String.valueOf( lp.getPassword() );
        }
        ld.dispose();
      }
      wB_UserPanel1.setDefaultScript( pScript );
      return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wB_UserPanel1 = new org.jecars.wb.WB_UserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify JeCARS User info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wB_UserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wB_UserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WB_UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jecars.wb.WB_UserPanel wB_UserPanel1;
    // End of variables declaration//GEN-END:variables

}
